parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Contracts\HttpClient\HttpClientInterface:
    class: \Symfony\Component\HttpClient\NativeHttpClient

  Isaev\WatchLog\:
    resource: '../src/'

  Isaev\WatchLog\Console\Application:
    public: true
    arguments:
      $name: 'Watch Log'
      $commands:
        - '@Isaev\WatchLog\Console\Command\Clear'
        - '@Isaev\WatchLog\Console\Command\Watch'
        - '@Isaev\WatchLog\Console\Command\Size'

  Isaev\WatchLog\Log\Handler\Telegram:
    arguments:
      $token: '%env(TELEGRAM_API_KEY)%'
      $chatId: '%env(TELEGRAM_CHAT_ID)%'

  Isaev\WatchLog\WatchLog:
    arguments:
      $handlers:
        - '@Isaev\WatchLog\Log\Handler\Console'
        - '@Isaev\WatchLog\Log\Handler\Telegram'
