parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Contracts\HttpClient\HttpClientInterface:
    class: \Symfony\Component\HttpClient\NativeHttpClient

  Isaev\WatchLog\:
    resource: '../src/'

  Isaev\WatchLog\Log\Handler\Telegram:
    arguments:
      $token: '%env(TELEGRAM_API_KEY)%'
      $chatId: '%env(TELEGRAM_CHAT_ID)%'

  Isaev\WatchLog\WatchLog:
    public: true
    arguments:
      $handlers:
        - '@Isaev\WatchLog\Log\Handler\Telegram'
        - '@Isaev\WatchLog\Log\Handler\Console'
